project_id = "tsxmfugpwgfzzxxtvscx"

[functions.delete-account]
verify_jwt = false

[functions.tarot-reading]
verify_jwt = false

[functions.runes-reading]
verify_jwt = false

[functions.mapa-astral]
verify_jwt = false
